/**
 * Standardized Error Messages for tools.
 *
 * Provides a consistent format for all error messages generated by
 * tool definitions and their execute() implementations. Every error
 * includes a context tag, the specific detail, and an optional hint.
 */

const HINT_SEPARATOR = '\n  \u{1F4A1} '; // 💡

/** Build a tagged error string. */
export function toolError(ctx: string, msg: string, hint?: string): string {
  let r = `[${ctx}] ${msg}`;
  if (hint) r += `${HINT_SEPARATOR}${hint}`;
  return r;
}

/** File-system related errors. */
export function fileNotFound(p: string): string {
  return toolError('FS', `File not found: ${p}`, 'Check the path and try again.');
}

/** Parameter validation errors (used by validate.ts). */
export function invalidParam(k: string, expect: string): string {
  return toolError('Validation', `"${k}" expected ${expect}`, 'Check the parameter value.');
}

/** Network-level errors. */
export function netError(url: string, detail: string): string {
  return toolError('Network', `${url}: ${detail}`, 'Check connectivity and URL.');
}

/** Git-related errors. */
export function gitError(op: string, detail: string): string {
  return toolError('Git', `${op}: ${detail}`, 'Run GitStatus to check repo state.');
}

/** Parse / format errors. */
export function parseError(fmt: string, detail: string): string {
  return toolError('Parse', `${fmt}: ${detail}`, 'Validate the input format.');
}
